export default {
  couple: {
    name1: 'Joselyn',
    name2: 'Paul',
    fullName1: 'Nombre completo novia,',
    fullName2: 'Nombre completo novio',
    initials: 'D&D',
    logo: '/logo.webp',
    namesFont: "'Alex Brush', cursive",
    parentNames1: {
      father: 'Nombre apellido Padre',
      mother: 'Nombre apellido Madre',
    },
    parentNames2: {
      father: 'Nombre apellido Padre',
      mother: 'Nombre apellido Madre',
    },
  },
  date: {
    weddingDate: '2026-05-30T13:00:00',
    displayDate: '30/05/2026',
    calendarMonthYear: 'Octubre 2026',
    rsvpDeadline: '30 de Mayo del 2025',
    calendarSelectedDate: '2026-05-30',
  },
  location: {
    city: 'Etzatlan Jalisco',
    church: {
      name: 'Templo',
      fullName: 'Templo de la Purísima Concepción',
      position: { lat: 20.76439604962931, lng: -104.08049966545539 },
      mapsUrl: 'https://www.google.com/maps/place/Parroquia+de+la+Purísima+Concepción/@20.7643749,-104.0830798,17z/data=!3m1!4b1!4m6!3m5!1s0x84247b3ef7dbbb17:0x1e83e8e7e0f8e6f8!8m2!3d20.76437!4d-104.0805!16s%2Fg%2F11c5b0q5m6?entry=ttu',
      icon: '/iglesiaBlanco.webp',
    },
    reception: {
      name: 'Recepción',
      fullName: 'El Ranchito, Escobedo #7',
      position: { lat: 20.76774609400717, lng: -104.09720436461963 },
      mapsUrl: 'https://maps.app.goo.gl/6pbkHd4kgUk2wsPu8',
      icon: '/papel-picado.webp',
    },
    mapCenter: 'church',
    mapZoom: 13,
  },
  contact: {
    groom: {
      label: 'Contacta al Novio',
      phone: '+52 3314857062',
      phoneRaw: '5213314857062',
      whatsappMessage: 'Hola Daniel y Daniela, quería contactarlos por su boda!',
    },
    bride: {
      label: 'Contacta a la Novia',
      phone: '+52 3334001701',
      phoneRaw: '5213334001701',
      whatsappMessage: 'Hola Daniel y Daniela, quería contactarlos por su boda!',
    },
  },
  bank: {
    name: 'BBVA',
    holder: 'Titular de la cuenta Bancaria',
    accountNumber: '2760430461',
    concept: 'Regalo de bodas',
  },
  gifts: {
    liverpoolUrl: '',
    liverpoolUrlAlt: '',
  },
  images: {
    hero: '/fotoHero.webp',
    promise: '/foto2.webp',
    timelineBottom: '/timeLine.webp',
    flowerCorner: '/flowerCorner.webp',
    simpleFlower: '/simpleFlower.webp',
    decorativeT: '/t.webp',
    disenoFloral1: '/diseno-floral.webp',
    disenoFloral2: '/diseno-floral-2.webp',
    disenoFloral3: '/diseno-floral-3.webp',
    petalo: '/petalo1.webp',
    novia: '/novia.webp',
    novio: '/novio.webp',
    dressCodeImg: '/dressCodeImg.webp',
    church: '/iglesia.webp',
    churchWhite: '/iglesiaBlanco.webp',
    papelPicado: '/papel-picado.webp',
    carousel: [
      '/us1.webp', '/us2.webp', '/us3.webp', '/us4.webp',
      '/us5.webp', '/us6.webp', '/us8.webp', '/us9.webp',
      '/us10.webp', '/us11.webp', '/us12.webp', '/us13.webp',
    ],
    timeline: {
      gettingReady: '/traje-de-boda.webp',
      ceremony: '/iglesia.webp',
      reception: '/animar.webp',
      banquet: '/banquete.webp',
      firstDance: '/baile.webp',
      party: '/pista-de-baile.webp',
      end: '/coche.webp',
    },
    dressCodeWomen: [
      '/vestidos1.webp', '/vestidos2.webp', '/vestidos3.webp', '/vestidos4.webp',
    ],
    dressCodeMen: [
      '/suits1.webp', '/suits2.webp', '/suits3.webp',
    ],
  },
  texts: {
    parentsIntro: 'Con nuestro amor y con la presencia de Dios entre nosotros y la bendición de nuestros padres:',
    countdown: {
      celebration: '🎉 ¡Es el gran día! ¡Felicidades! 💍',
      remaining: 'Faltan:',
      days: 'días',
      hours: 'horas',
      minutes: 'min',
      seconds: 'seg',
    },
    saveDate: 'Save The Date',
    promise: {
      title: 'UNA PROMESA PARA TODA LA VIDA',
      text: 'Nos conocimos en el 2015 y desde ese momento sentimos esa conexión. Sin embargo, no fue hasta finales del 2018 donde volvimos a reconectar y el resto es historia. Desde ese momento supimos que éramos el uno para el otro. Cada risa compartida, cada abrazo y cada sueño construido nos llevó hasta aquí. Ahora, con el corazón lleno de amor y emoción, damos el siguiente paso: unir nuestras vidas para siempre.',
    },
    timeline: {
      title: 'Wedding Time Line',
      events: [
        { time: '12:00 PM', title: 'Getting Ready', description: '', icon: 'gettingReady' },
        { time: '1:00 PM', title: 'Misa Religiosa', description: 'Ceremonia religiosa', icon: 'ceremony' },
        { time: '3:00 PM', title: 'Inicio de la recepción', description: 'Bienvenida y cóctel', icon: 'reception' },
        { time: '4:00 PM', title: 'Banquete', description: '', icon: 'banquet' },
        { time: '6:00 PM', title: 'Primer Vals', description: '', icon: 'firstDance' },
        { time: '7:00 PM', title: 'Inicio de la fiesta', description: '', icon: 'party' },
        { time: '1:00 AM', title: 'Fin de la recepción', description: '', icon: 'end' },
      ],
    },
    calendar: {
      dayNames: ['Don', 'Lue', 'Med', 'Jri', 'Vat', 'Sun'],
      selectedDayLabel: 'El Gran Día',
    },
    confirmation: {
      title: 'Confirme su asistencia',
      codeLabel: 'Codigo',
      codePlaceholder: 'ABXY2025',
      codeHelp: 'Codigo proporcionado en su invitacion.',
      button: 'Confirmar Asistencia',
      loading: 'Buscando...',
      notFound: 'Invitado no encontrado',
      error: 'Error al buscar el invitado',
    },
    confirmPage: {
      title: 'Confirma tu Asistencia',
      familyMessage: '✨ "Nos emociona compartir este momento tan especial con las personas que más queremos. Para ayudarnos a planear este día tan importante, por favor confirme su asistencia y la de su familia.',
      companionMessage: '✨ "Nos emociona compartir este momento tan especial con las personas que más queremos. Para ayudarnos a planear este día tan importante, por favor confirme su asistencia y la de sus acompañantes.',
      nameLabel: 'Nombre',
      confirmedLabel: 'confirmado',
      submitButton: 'Confirmar Asistencia',
      adultsOnlyEnabled: false,
      adultsOnly: 'Celebración exclusiva para ADULTOS.',
      adultsOnlyLink: 'https://www.tiktok.com/@gabylajarochita.83/video/7316280366153633030?is_from_webapp=1&lw_scan=1&shortcut_feature=feed',
      footer: 'Para más información, contacta a los novios.',
      footerThanks: '¡Gracias por ser parte de nuestro día especial!',
      backButton: 'Atrás',
      modalTitle: 'Confirmar Asistencia',
      modalMessage: '¿Estás seguro de que deseas confirmar?',
      successMessage: '¡Confirmación enviada con éxito!',
      errorMessage: 'Hubo un error al confirmar asistencia.',
    },
    dressCode: {
      title: 'Dress Code',
      intro: 'Queremos asegurarnos que todos se sientan cómodos y en sintonía con la celebración',
      level: 'Formal',
      womenLabel: 'Ellas',
      womenDescription: 'Vestidos florales, colores claros o tonos coloridos',
      womenRestriction: 'No Negro, Lila o Rojo',
      menLabel: 'Ellos',
      menDescription: 'Vestimenta elegante,',
      menRestriction: 'No Verde olivo',
      danceTitle: 'Preparate para Bailar',
      danceDescription: 'La fiesta no para, así que asegúrate de traer zapatos cómodos.',
      danceSuggestion: 'Sugerimos Tenis',
      womenCarouselTitle: 'Algunas ideas para ellas',
      menCarouselTitle: 'Algunas ideas para ellos',
    },
    contact: {
      title: 'Contacta a los novios',
    },
    gifts: {
      title: 'Regalos',
      intro: '¡Tu presencia es el mejor regalo! Pero si deseas contribuir, aquí tienes algunas opciones:',
      giftButton: 'Mesa de Regalos',
      bankButton: 'Datos Bancarios',
      footer: 'Para más información, contacta a los novios.',
      footerThanks: '¡Gracias por ser parte de nuestro día especial!',
    },
    bankPage: {
      title: 'Banco de Regalos',
      intro: 'Su presencia es lo más importante para nosotros, pero si desean hacernos un regalo, hemos creado un banco de regalos para facilitarlo. Aquí pueden encontrar los datos bancarios para hacer una transferencia.',
      giftButton: 'Mesa de Regalos Liverpool',
      footer: 'Para más información, contacta a los novios.',
      footerThanks: '¡Gracias por ser parte de nuestro día especial!',
      backButton: 'Atrás',
    },
    copy: 'Copiar',
    copied: '¡Número copiado!',
    nav: {
      giftRegistry: 'Mesa de Regalos',
      requestInfo: 'Solicitar Informacion',
      location: 'Ubicacion',
      dressCode: 'Codigo de Vestimenta',
      confirmAttendance: ' ',
    },
    footer: '© 2025 Realizado por Masolutions.',
    modal: {
      title: '¿Estás seguro?',
      message: 'Esta acción no se puede deshacer.',
      confirm: 'Aceptar',
      cancel: 'Cancelar',
    },
  },
  guestSides: {
    side1: 'NOVIO',
    side2: 'NOVIA',
    side1Label: 'Novio',
    side2Label: 'Novia',
  },
}
